# DataSource Config
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://116.205.167.248:3306/databrain?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
        username: test
        password: Aa12345!

system:
    bcos-cfg: "bcos/config.toml"
    crypto-type: 0
    salt: "salt_string"
    witness-private-key: '0x'
    contract:
        account-contract: "0x"
