server:
    port: 10880

spring:
    mvc:
        async:
            request-timeout: 500
    datasource:
#        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://116.205.167.248:3306/databrain2?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: test
        password: Aa12345!
        driverClassName: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        defaultAutoCommit: false
        initialSize: 25
        maxActive: 128
        maxIdle: 50
        minIdle: 25
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        validationQuery: SELECT 1
        timeBetweenEvictionRunsMillis: 34000
        minEvictableIdleTimeMillis: 34000
        removeAbandoned: false
        logAbandoned: true
        removeAbandonedTimeout: 54
        maxWait: 10000
        poolPreparedStatements: false
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

mybatis:
    typeAliasesPackage: com.webank.databrain.dao.entity
    configuration:
        map-underscore-to-camel-case: true

system:
    bcos-cfg: "config/config.toml"
    bcos-group-id: "group0"
    crypto-type: 0
    salt: "salt_string"
    witness-private-key: '11afa82f974469792aa0172931b813d4fc7dd9177f3211779efc5f955d5e480f'
    contractConfig:
        account-contract: "0x963f375f4d1d1969bbd318628910d080506131b4"
        product-contract: "0xb3aa7a6f43eb2cb0cf2099f4f5e170efc63ee1d0"
        dataSchema-contract: "0xe7d7b002e51431b300ddc00b2c059ccc41ce4660"
    loginConfig:
        token-expire-minutes: 2880
    fileConfig:
        file-dir: "tmp"
swagger:
    enabled: true


